"""Build a human-readable index of committed pretrained checkpoints.

Reviewers (and a resuming run) need to know *what* each ``.pt`` under
``artifacts/checkpoints/`` is without loading all of them. Every checkpoint is
self-describing (it stores its ``config_hash``, backbone, task, and the real
train/val/test metrics from the run that produced it), so this module simply
scans them and emits a manifest. Nothing here is hand-entered: every field is
read back out of the checkpoint payload written by ``train_model``.

Run as::

    python -m molsanity.models.checkpoint_manifest

which writes ``artifacts/checkpoints/MANIFEST.md`` and ``.../MANIFEST.json``.
"""
from __future__ import annotations

import json
from pathlib import Path

import torch

CKPT_ROOT = Path("artifacts") / "checkpoints"


def _fmt(v) -> str:
    if v is None:
        return "—"
    if isinstance(v, float):
        if v != v:  # NaN
            return "—"
        return f"{v:.4f}"
    return str(v)


def scan_checkpoints(root: Path = CKPT_ROOT) -> list[dict]:
    """Read every top-level (non-``_early``) checkpoint into a manifest row.

    ``_early`` intermediate checkpoints are recorded only as a flag on their
    parent row, since they share the parent's config and exist for the
    cross-checkpoint stability metric.
    """
    rows: list[dict] = []
    if not root.exists():
        return rows
    for pt in sorted(root.rglob("*.pt")):
        if pt.stem.endswith("_early"):
            continue
        payload = torch.load(pt, map_location="cpu", weights_only=False)
        early = pt.with_name(f"{pt.stem}_early.pt")
        rows.append({
            "dataset": pt.parent.name,
            "backbone": payload.get("backbone", pt.stem.split("_")[0]),
            "task": payload.get("task", ""),
            "config_hash": payload.get("config_hash", pt.stem.split("_", 1)[-1]),
            "path": str(pt.as_posix()),
            "has_early": early.exists(),
            "epochs_run": payload.get("epochs_run"),
            "test_acc": payload.get("test_acc"),
            "test_auc": payload.get("test_auc"),
            "test_rmse": payload.get("test_rmse"),
            "test_r2": payload.get("test_r2"),
            "test_ece": payload.get("test_ece"),
            "temperature": payload.get("temperature"),
        })
    return rows


def write_manifest(root: Path = CKPT_ROOT) -> tuple[Path, Path]:
    rows = scan_checkpoints(root)
    json_path = root / "MANIFEST.json"
    md_path = root / "MANIFEST.md"
    json_path.write_text(json.dumps(rows, indent=2) + "\n")

    n_cls = sum(1 for r in rows if r["task"] == "graph-classification")
    n_reg = sum(1 for r in rows if r["task"] == "graph-regression")
    n_early = sum(1 for r in rows if r["has_early"])
    lines = [
        "# Committed pretrained checkpoints",
        "",
        "> Auto-generated by `python -m molsanity.models.checkpoint_manifest`.",
        "> Every field is read back out of the checkpoint payload written by the",
        "> training run — nothing here is hand-entered. Each checkpoint stores its",
        "> `config_hash`; a re-run of `run_all` with the matching config recomputes",
        "> the same hash, hits this file as a cache, and resumes without retraining.",
        "",
        f"**{len(rows)} checkpoints** "
        f"({n_cls} classification · {n_reg} regression) · "
        f"{n_early} with an `_early` intermediate (for cross-checkpoint stability).",
        "",
        "| dataset | backbone | task | config_hash | epochs | test_acc | test_auc "
        "| test_rmse | test_r2 | test_ece | temp | early |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for r in sorted(rows, key=lambda r: (r["dataset"], r["backbone"], r["config_hash"])):
        task_short = {"graph-classification": "cls", "graph-regression": "reg"}.get(
            r["task"], r["task"] or "—")
        lines.append(
            f"| {r['dataset']} | {r['backbone']} | {task_short} | `{r['config_hash']}` "
            f"| {_fmt(r['epochs_run'])} | {_fmt(r['test_acc'])} | {_fmt(r['test_auc'])} "
            f"| {_fmt(r['test_rmse'])} | {_fmt(r['test_r2'])} | {_fmt(r['test_ece'])} "
            f"| {_fmt(r['temperature'])} | {'✓' if r['has_early'] else '—'} |"
        )
    lines.append("")
    md_path.write_text("\n".join(lines))
    return md_path, json_path


def main() -> None:
    md_path, json_path = write_manifest()
    rows = json.loads(json_path.read_text())
    print(f"Wrote {md_path} and {json_path} ({len(rows)} checkpoints).")


if __name__ == "__main__":
    main()
