"""The supplementary bundle must be the reports, not a snapshot of them.

Supplementary material is uploaded once and then forgotten, which is exactly
how a reviewer ends up reading numbers the paper no longer reports. The bundle
is generated by copying from results/, so this asserts the copies are current.
"""
from __future__ import annotations

from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
BUNDLE = ROOT / "paper" / "supplementary"
SRC = ROOT / "results"


def test_bundle_is_byte_identical_to_the_committed_reports():
    if not BUNDLE.exists():
        pytest.skip("supplementary bundle not generated; run 'make -C paper supplementary'")
    stale = []
    for f in sorted(BUNDLE.glob("*.md")):
        if f.name == "README.md":       # written by the generator, not copied
            continue
        origin = SRC / f.name
        assert origin.exists(), f"{f.name} is in the bundle but not in results/"
        if f.read_bytes() != origin.read_bytes():
            stale.append(f.name)
    assert not stale, (
        "supplementary copies differ from results/: " + ", ".join(stale)
        + "\nRun 'make -C paper supplementary'. Never edit files in the bundle.")


def test_the_seed_variance_report_is_in_the_bundle():
    """The one file the manuscript explicitly promises a reader.

    The selection tests are single-seed by construction -- a paired
    per-molecule test needs the same molecules on both sides, and the split is
    a function of the seed -- so the across-seed spread is the check on them,
    and the paper says it is supplementary material.
    """
    if not BUNDLE.exists():
        pytest.skip("supplementary bundle not generated")
    assert (BUNDLE / "SEED_VARIANCE.md").exists()
    # LaTeX wraps prose, so normalise whitespace before looking for a phrase.
    body = " ".join((ROOT / "paper" / "body.tex").read_text().split())
    assert "supplementary material" in body, (
        "the bundle exists but the manuscript never points a reader at it")
