"""The supplementary bundle must be the reports, not a snapshot of them.

Supplementary material is uploaded once and then forgotten, which is exactly
how a reviewer ends up reading numbers the paper no longer reports. The bundle
is generated by copying from results/, so this asserts the copies are current.
"""
from __future__ import annotations

from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
BUNDLE = ROOT / "paper" / "supplementary"
SRC = ROOT / "results"


def test_bundle_is_byte_identical_to_the_committed_reports():
    if not BUNDLE.exists():
        pytest.skip("supplementary bundle not generated; run 'make -C paper supplementary'")
    stale = []
    for f in sorted(BUNDLE.glob("*.md")):
        if f.name == "README.md":       # written by the generator, not copied
            continue
        origin = SRC / f.name
        assert origin.exists(), f"{f.name} is in the bundle but not in results/"
        if f.read_bytes() != origin.read_bytes():
            stale.append(f.name)
    assert not stale, (
        "supplementary copies differ from results/: " + ", ".join(stale)
        + "\nRun 'make -C paper supplementary'. Never edit files in the bundle.")


def test_the_seed_variance_report_is_in_the_bundle():
    """The one file the manuscript explicitly promises a reader.

    The selection tests are single-seed by construction -- a paired
    per-molecule test needs the same molecules on both sides, and the split is
    a function of the seed -- so the across-seed spread is the check on them,
    and the paper says it is supplementary material.
    """
    if not BUNDLE.exists():
        pytest.skip("supplementary bundle not generated")
    assert (BUNDLE / "SEED_VARIANCE.md").exists()
    # LaTeX wraps prose, so normalise whitespace before looking for a phrase.
    body = " ".join((ROOT / "paper" / "body.tex").read_text().split())
    # The manuscript now names the numbered additional file rather than the
    # generic phrase: BMC requires each file to be cited by its number, and
    # "supplementary material" satisfies no technical check.
    assert "Additional file~3" in body or "Additional file 3" in body, (
        "the across-seed spread is bundled but the manuscript never points a "
        "reader at it by number")


def test_no_working_document_is_bundled():
    """Supplementary material is generated reports, not working documents.

    LIMITATIONS.md shipped in this bundle for exactly one commit. It is a
    hand-maintained register, current for whoever is building the thing and
    free to describe a run that is no longer the reported one -- and it did:
    the regression cells "are excluded from every faithfulness claim until the
    next sweep", the shift contrast resting on MUTAG and MolMotif. The
    manuscript has a test forbidding those sentences in its own prose, so
    attaching them as supplementary material reintroduced the contradictions
    through the side door.
    """
    import importlib.util

    spec = importlib.util.spec_from_file_location(
        "make_supplementary", ROOT / "paper" / "make_supplementary.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    overlap = mod.BUNDLE.keys() & mod.NEVER_BUNDLE
    assert not overlap, f"working documents in the bundle: {sorted(overlap)}"
    if BUNDLE.exists():
        on_disk = {f.name for f in BUNDLE.glob("*.md")} - {"README.md"}
        assert not (on_disk & mod.NEVER_BUNDLE), (
            "a working document is sitting in paper/supplementary/: "
            f"{sorted(on_disk & mod.NEVER_BUNDLE)}")


def test_bundled_reports_carry_no_in_progress_language():
    """A generated report describes a finished run, or it is not shippable.

    "being recomputed", "until the next sweep", "are withdrawn" are all true
    of a repository mid-correction and all wrong in a file attached to a
    submission, where a reviewer reads them as describing the work they are
    assessing.
    """
    import re

    if not BUNDLE.exists():
        pytest.skip("supplementary bundle not generated")
    bad = re.compile(
        r"being recomputed|next sweep|are withdrawn|development environment"
        r"|\bTODO\b|\bFIXME\b|\bWIP\b", re.I)
    hits = []
    for f in sorted(BUNDLE.glob("*.md")):
        for i, line in enumerate(f.read_text().splitlines(), 1):
            if bad.search(line):
                hits.append(f"{f.name}:{i}: {line.strip()[:90]}")
    assert not hits, "in-progress language in supplementary material:\n  " + \
        "\n  ".join(hits)


def test_additional_files_are_numbered_declared_and_cited_in_order():
    """BMC's additional-file rules, which a .md bundle did not satisfy.

    The submission form takes numbered "Additional file N" items, each listed
    in the manuscript with its file name and a description, and each cited in
    sequence in the main text. The previous bundle was five raw .md reports:
    unnumbered, undeclared, uncited, and in a format BMC does not list. This
    asserts the three rules that a reader or a technical check would apply.
    """
    import re

    paper = ROOT / "paper"
    body = " ".join((paper / "body.tex").read_text().split())

    declared = set(int(n) for n in re.findall(
        r"\\textbf\{Additional file (\d+)\}", body))
    assert declared, "the manuscript declares no additional files"
    assert declared == set(range(1, max(declared) + 1)), \
        f"additional files are not numbered consecutively: {sorted(declared)}"

    # Citations in the body, excluding the declaration list itself.
    decl_at = body.find(r"\paragraph{Additional files}")
    prose = body[:decl_at] if decl_at > 0 else body
    cited = [int(n) for n in re.findall(r"Additional file~?\\?~?(\d+)", prose)]
    first = []
    for n in cited:
        if n not in first:
            first.append(n)
    assert first == sorted(first), (
        f"additional files are not cited in sequence: first mentions {first}")
    assert set(first) == declared, (
        f"declared {sorted(declared)} but cited {sorted(set(first))}")

    out = paper / "submission"
    if not out.exists():
        pytest.skip("submission package not built; run 'make -C paper submission-files'")
    for n in sorted(declared):
        hits = list(out.glob(f"Additional_file_{n}.*"))
        assert hits, f"Additional file {n} is declared but not built"
        for f in hits:
            assert f.stat().st_size <= 20 * 1024 * 1024, \
                f"{f.name} exceeds BMC's 20 MB per-file limit"


def test_the_manuscript_upload_is_an_editable_source_archive():
    """The submission form does not take a PDF as the manuscript file.

    It takes a Word document, or LaTeX with figures compressed into a .zip
    which the publisher compiles. A PDF-only delivery cannot be submitted, so
    the package has to carry sources that build on their side: every file
    main.tex \\input{}s must be inside the archive.
    """
    import re
    import zipfile

    zpath = ROOT / "paper" / "submission" / "molsanity_latex_sources.zip"
    if not zpath.exists():
        pytest.skip("source archive not built; run 'make -C paper submission-files'")
    names = set(zipfile.ZipFile(zpath).namelist())
    assert "main.tex" in names, "the archive has no main.tex"

    main = (ROOT / "paper" / "main.tex").read_text()
    body = (ROOT / "paper" / "body.tex").read_text()
    missing = []
    for src in (main, body):
        for inc in re.findall(r"\\(?:input|include)\{([^}]+)\}", src):
            if not any(n == inc or n == inc + ".tex" for n in names):
                missing.append(inc)
        for img in re.findall(r"\\includegraphics(?:\[[^\]]*\])?\{([^}]+)\}", src):
            if not any(n == img or n.startswith(img + ".") for n in names):
                missing.append(img)
    assert not missing, f"the archive is missing inputs the manuscript needs: {missing}"


def test_the_supplementary_pdf_carries_no_raw_markdown():
    """Additional file 1 is typeset from markdown, so markers can leak.

    The first build printed "_Faithfulness-only selection test_" and "the
    *ground truth* says is best" with their markers intact, and rendered the
    star that flags the ground-truth-best attributor as an empty box because
    the text font has no U+2B50. Both are only visible by opening the PDF.

    The generator already fails the build on a character the font cannot set;
    this covers the other half -- markup that survived the converter.
    """
    import re

    tex = ROOT / "paper" / "submission" / "Additional_file_1.tex"
    if not tex.exists():
        pytest.skip("submission package not built; run 'make -C paper submission-files'")
    body = tex.read_text()
    body = body.split(r"\begin{document}", 1)[-1]
    leftovers = []
    for pattern, what in [(r"\*\*", "bold markers"),
                          (r"(?<![\\\w])\*(?=\S)", "italic markers"),
                          (r"(?<!\\)`", "code backticks"),
                          (r"^\s*[-*]\s+\S", "unconverted list bullets"),
                          (r"^\s*\|", "unconverted markdown table row"),
                          (r"^\s*#{1,6}\s", "unconverted heading")]:
        if re.search(pattern, body, re.M):
            leftovers.append(what)
    assert not leftovers, (
        "raw markdown survived into Additional file 1: " + ", ".join(leftovers))
