"""Collect every generated figure into one tracked, browsable folder.

Figures are produced under ``artifacts/figures/`` (regenerable, gitignored). That
makes them awkward to look at or review. This module mirrors them into
``figures/`` — which *is* committed — with a stable layout and a generated
``INDEX.md`` so a reader can browse the whole visual record without running
anything:

    figures/
      key/       the headline figures the paper leads with
      summary/   cross-matrix figures (heatmaps, ECDFs, regimes, composites)
      cells/     per-(dataset × backbone × attributor × split) figures
      INDEX.md   generated contents listing

Nothing here computes results — it only copies and indexes what the pipeline
already rendered.
"""
from __future__ import annotations

import shutil
from pathlib import Path

SRC_ROOT = Path("artifacts") / "figures"
DEST_ROOT = Path("figures")

# Figures promoted to figures/key/ — the ones the paper leads with.
KEY_FIGURES = {
    "dissociation": "Capstone: faithfulness vs ground truth, in-distribution "
                    "vs under scaffold shift.",
    "results_composite": "Composite of the headline result panels.",
    "joint_faithful_correct": "Faithfulness vs correctness, with the "
                              "faithful-but-wrong quadrant marked.",
    "heatmap_gt": "Ground-truth localisation across the whole audit matrix.",
}

# Human-readable notes for the recurring figure basenames.
DESCRIPTIONS = {
    "dissociation": "**Capstone.** Faithfulness tracks ground truth "
                    "in-distribution (ρ≈+0.77) but not under scaffold shift "
                    "(ρ≈−0.49), where a fidelity-only ranking picks the wrong "
                    "attributor (p<0.001).",
    "results_composite": "Multi-panel composite of the headline results.",
    "joint_faithful_correct": "Joint distribution of occlusion faithfulness and "
                              "ground-truth AUROC, with marginals.",
    "heatmap_gt": "Ground-truth AUROC per dataset × backbone × attributor.",
    "attributor_gt_bar": "Ground-truth localisation by attributor.",
    "faithfulness_stability_ecdf": "ECDFs of faithfulness and cross-checkpoint "
                                   "stability.",
    "regime_stratification": "Metrics stratified by confidence/correctness regime.",
    "raincloud_gt": "Per-molecule ground-truth AUROC distribution.",
    "molgrid": "RDKit molecule grid with attribution overlays.",
    "gt_validation": "Attribution vs ground-truth motif mask for this cell.",
    "case_molecule": "Single-molecule attribution rendering.",
}


def _describe(stem: str) -> str:
    for key, text in DESCRIPTIONS.items():
        if stem.startswith(key):
            return text
    return ""


def _copy(src: Path, dest: Path) -> bool:
    """Copy only when content differs, so re-runs don't churn the git diff."""
    dest.parent.mkdir(parents=True, exist_ok=True)
    if dest.exists() and dest.stat().st_size == src.stat().st_size and \
            dest.read_bytes() == src.read_bytes():
        return False
    shutil.copy2(src, dest)
    return True


def collect_figures(src_root: Path = SRC_ROOT, dest_root: Path = DEST_ROOT) -> dict:
    """Mirror artifacts/figures -> figures/ and write figures/INDEX.md."""
    src_root, dest_root = Path(src_root), Path(dest_root)
    dest_root.mkdir(parents=True, exist_ok=True)
    copied, seen = 0, 0

    summary_files: list[Path] = []
    cell_files: dict[str, list[Path]] = {}

    if src_root.exists():
        for f in sorted(src_root.rglob("*")):
            if f.suffix.lower() not in {".pdf", ".svg", ".png"}:
                continue
            seen += 1
            rel_parent = f.parent.name
            if rel_parent == "_summary":
                dest = dest_root / "summary" / f.name
                summary_files.append(dest)
            else:
                dest = dest_root / "cells" / rel_parent / f.name
                cell_files.setdefault(rel_parent, []).append(dest)
            copied += int(_copy(f, dest))

            # Promote the headline figures into key/ as well.
            if f.stem in KEY_FIGURES and rel_parent == "_summary":
                copied += int(_copy(f, dest_root / "key" / f.name))

    key_files = sorted((dest_root / "key").glob("*")) if (dest_root / "key").exists() else []
    _write_index(dest_root, key_files, sorted(summary_files), cell_files)
    return {"scanned": seen, "copied": copied,
            "n_key": len({p.stem for p in key_files}),
            "n_summary": len({p.stem for p in summary_files}),
            "n_cells": len(cell_files)}


def _stems(paths) -> list[str]:
    return sorted({Path(p).stem for p in paths})


def _write_index(dest_root: Path, key_files, summary_files, cell_files) -> None:
    lines = [
        "# Figure index",
        "",
        "_Generated by `python -m molsanity.viz.collect` (also run at the end of",
        "every pipeline run). Every figure is vector **PDF + SVG**; the source of",
        "truth for the numbers behind them is `RESULTS.md` / `BENCHMARK_GT.md`._",
        "",
        f"**{len(_stems(key_files))} key** · **{len(_stems(summary_files))} summary** · "
        f"**{len(cell_files)} per-cell** figure sets.",
        "",
        "## Key figures",
        "",
        "| figure | what it shows |",
        "| --- | --- |",
    ]
    for stem in _stems(key_files):
        lines.append(f"| [`key/{stem}.pdf`](key/{stem}.pdf) | {_describe(stem)} |")
    if not key_files:
        lines.append("| _(none yet — run the pipeline)_ | |")

    lines += ["", "## Cross-matrix summary figures", "",
              "| figure | what it shows |", "| --- | --- |"]
    for stem in _stems(summary_files):
        lines.append(f"| [`summary/{stem}.pdf`](summary/{stem}.pdf) | {_describe(stem)} |")
    if not summary_files:
        lines.append("| _(none yet)_ | |")

    lines += ["", "## Per-cell figures", "",
              "One folder per audited cell "
              "(`dataset__backbone__attributor__split`), each with the "
              "ground-truth validation panel and, for molecular datasets, a "
              "rendered case molecule.", "",
              "| cell | files |", "| --- | --- |"]
    for cell in sorted(cell_files):
        stems = _stems(cell_files[cell])
        lines.append(f"| [`cells/{cell}/`](cells/{cell}/) | {', '.join(stems)} |")
    if not cell_files:
        lines.append("| _(none yet)_ | |")
    lines.append("")
    (dest_root / "INDEX.md").write_text("\n".join(lines))


def main() -> None:
    info = collect_figures()
    print(f"Collected figures -> {DEST_ROOT}/ "
          f"(scanned {info['scanned']}, copied {info['copied']}; "
          f"{info['n_key']} key, {info['n_summary']} summary, "
          f"{info['n_cells']} cells). Wrote {DEST_ROOT}/INDEX.md")


if __name__ == "__main__":
    main()
