"""Assemble the supplementary bundle from the committed reports.

    python paper/make_supplementary.py

Copies -- never edits -- the generated reports under ``results/`` into
``paper/supplementary/`` and writes an index. Copying rather than linking is
what a preprint server and a journal both want (a folder of files to upload),
and copies drift, so ``tests/test_supplementary.py`` asserts byte equality with
``results/`` and the Makefile regenerates the bundle on every build.

The bundle exists because of one thing in particular: the selection tests in
the manuscript are computed within a single seed -- a paired per-molecule test
needs the same molecules on both sides, and the split is a function of the seed
-- so a reader who wants to know how much of a reported ranking is seed noise
needs SEED_VARIANCE.md, and should not have to clone the repository to get it.
"""
from __future__ import annotations

import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "results"
OUT = Path(__file__).resolve().parent / "supplementary"

# file -> one line saying why a reviewer would open it
BUNDLE = {
    "SEED_VARIANCE.md":
        "Across-seed mean, standard deviation, min and max for every cell run "
        "under more than one seed. Read this against any attributor ranking in "
        "the manuscript: an effect smaller than the spread here is not "
        "evidence. It is the companion to the single-seed selection tests.",
    "BENCHMARK_GT.md":
        "The faithfulness-versus-ground-truth selection experiment as the "
        "pipeline emitted it, including the per-cell conclusions generated "
        "from the computed results.",
    "BENCHMARK.md":
        "Head-to-head attributor comparison over the full matrix, including "
        "the framework metrics (Fidelity+/-, characterisation, unfaithfulness) "
        "reproduced from the canonical implementations.",
    "RATIONALE_USE.md":
        "The rationale-use test: occluding the ground-truth substructure and "
        "measuring whether the prediction collapses, which is what separates "
        "'the attribution is wrong' from 'the model uses a different rationale'.",
    "ABSTENTION.md":
        "Coverage-reliability curves for selective prediction on explanations "
        "-- what an audit buys a practitioner who can abstain.",
    "LIMITATIONS.md":
        "The maintained limitations register, longer than the manuscript's "
        "limitations section and including items that did not survive editing.",
}


def main() -> None:
    OUT.mkdir(exist_ok=True)
    missing = [n for n in BUNDLE if not (SRC / n).exists()]
    if missing:
        raise SystemExit(f"missing reports in results/: {missing}")

    lines = [
        "# Supplementary material",
        "",
        "Generated by `paper/make_supplementary.py` from the committed reports "
        "under `results/`. Every file here is a byte-for-byte copy; nothing in "
        "this folder is written by hand.",
        "",
        "The full pipeline, configurations, trained checkpoints and "
        "per-molecule audit records are at "
        "<https://github.com/Kar488/molsanity> under the MIT licence.",
        "",
    ]
    for name, why in BUNDLE.items():
        shutil.copy2(SRC / name, OUT / name)
        lines += [f"## `{name}`", "", why, ""]
        print(f"  copied {name}")

    (OUT / "README.md").write_text("\n".join(lines))
    print(f"  wrote {OUT / 'README.md'}")


if __name__ == "__main__":
    main()
